[
	Constructor(DOMString event_type,
				DOMString message_type,
				DOMString param1,
				DOMString param2),
	Exposed=Window
] interface TangramEvent : Event {
	attribute DOMString messageType;
	attribute DOMString param1;
	attribute DOMString param2;
};
