typedef sequence<any> ObjectArray;

[
	Exposed = Window, 
	NoInterfaceObject 
] interface Tangram : EventTarget {

	// Internal API
	void ipcMessage__(DOMString type, DOMString param1, DOMString param2);

	// Message API
	void addChannel(DOMString channel);
	void removeChannel(DOMString channel);
	void sendMessage(DOMString channel, DOMString data);

	// Event handler attributes
	attribute EventHandler onMessageReceived;

	// DOM API
	void defineElement(DOMString tagName, DOMString html);
	void renderElement(DOMString tagName, DOMString html);
};
